### 게시글 생성
POST http://localhost:8080/community
Content-Type: application/json

 {
   "communityName" : "게시글 제목 1",
   "content" : "게시글 내용 1",
   "communityPublicState" : false,
   "shareId" : 1
 }

### 게시글 목록 조회
GET localhost:8080/community?page=0&size=10&sort=recent

### 특정 게시글 조회
GET localhost:8080/api/community/933